In [18]:
import numpy as np

arithmetic operations and functions

In [2]:
a = np.arange(1,11)
b = np.arange(21,31)
print('a',a)
print('b',b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [3]:
a + b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [4]:
b - a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [5]:
a * b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [6]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [7]:
c = np.arange(2,12)
print('c',c)

c [ 2  3  4  5  6  7  8  9 10 11]


In [8]:
a**c

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [9]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [11]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [12]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [13]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [14]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [15]:
np.power(a,c)

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [16]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

broadcasting

In [19]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [21]:
a + b # added array a to every row in b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [22]:
c = np.arange(1,3)
c

array([1, 2])

In [23]:
a + c # unable to do since c has less columns than a

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [24]:
d = np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [27]:
d - e # subtracted every row of d from e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

aggregate functions

In [29]:
first_arr = np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [30]:
second_arr = np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [31]:
third_arr = np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [32]:
first_arr.sum()

550

In [33]:
second_arr.sum()

450

In [35]:
third_arr.sum()

550

In [36]:
second_arr.sum(axis=0) # sums the columns

array([120, 150, 180])

In [38]:
second_arr.sum(axis=1) #sums the row

array([ 60, 150, 240])

In [39]:
first_arr.prod()

36288000000000000

In [40]:
second_arr.prod()

362880000000000

In [41]:
third_arr.prod()

36288000000000000

In [42]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [43]:
np.average(first_arr)

55.0

In [44]:
np.average(second_arr)

50.0

In [45]:
np.average(third_arr)

55.0

In [46]:
np.min(first_arr)

10

In [47]:
np.max(first_arr)

100

In [48]:
np.mean(first_arr)

55.0

In [49]:
np.std(first_arr)

28.722813232690143

unique items and counts

In [50]:
first_arr = np.array([1,2,3,4,5,6,1,2,7,2,1,10,9,8])

In [51]:
np.unique(first_arr) #finds the unique elements in the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
second_arr = np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [53]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [54]:
np.unique(second_arr,axis = 0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [55]:
np.unique(second_arr,axis =1 )

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [56]:
np.unique(first_arr,return_index=True)#2nd array is the unique elements

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 12, 11]))