In [2]:
import numpy as np

In [4]:
first_arr = np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [5]:
new_frist_arr = np.insert(first_arr,3,4) 
new_frist_arr

array([1, 2, 3, 4, 5])

In [6]:
second_arr = np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [7]:
new_second_arr = np.append(second_arr, 5)
new_second_arr

array([1, 2, 3, 4, 5])

In [8]:
third_arr = np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [9]:
del_arr = np.delete(third_arr, 4)
del_arr

array([1, 2, 3, 4])

In [10]:
integers_arr = np.random.randint(0,20,20)
integers_arr

array([18, 16,  7, 15,  0,  5,  7,  9, 14,  8,  9, 14, 15, 14,  0, 19,  2,
       15, 17,  7])

In [11]:
print(np.sort(integers_arr))

[ 0  0  2  5  7  7  7  8  9  9 14 14 14 15 15 15 16 17 18 19]


In [13]:
integers_2dim_arr = np.array([[3,2,5,7,4],[5,0,8,3,1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [14]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [15]:
colors = np.array(['violet', 'orange', 'yellow', 'white', 'black'])
colors

array(['violet', 'orange', 'yellow', 'white', 'black'], dtype='<U6')

In [16]:
print(np.sort(colors))

['black' 'orange' 'violet' 'white' 'yellow']
