In [2]:
import numpy as np

adding, removing and sorting elements

In [4]:
first_arr = np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [5]:
new_frist_arr = np.insert(first_arr,3,4) # inserted 4 at index 3
new_frist_arr

array([1, 2, 3, 4, 5])

In [6]:
second_arr = np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [7]:
new_second_arr = np.append(second_arr, 5) # added 5 at the end
new_second_arr

array([1, 2, 3, 4, 5])

In [8]:
third_arr = np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [9]:
del_arr = np.delete(third_arr, 4) #deleted element at index 4
del_arr

array([1, 2, 3, 4])

In [10]:
integers_arr = np.random.randint(0,20,20)
integers_arr

array([18, 16,  7, 15,  0,  5,  7,  9, 14,  8,  9, 14, 15, 14,  0, 19,  2,
       15, 17,  7])

In [11]:
print(np.sort(integers_arr)) # sorted the array

[ 0  0  2  5  7  7  7  8  9  9 14 14 14 15 15 15 16 17 18 19]


In [13]:
integers_2dim_arr = np.array([[3,2,5,7,4],[5,0,8,3,1]]) #sorted the 2d array
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [14]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [15]:
colors = np.array(['violet', 'orange', 'yellow', 'white', 'black'])
colors

array(['violet', 'orange', 'yellow', 'white', 'black'], dtype='<U6')

In [16]:
print(np.sort(colors)) #sorted an array of strings

['black' 'orange' 'violet' 'white' 'yellow']


copies and views

In [18]:
students_ids_number = np.array([1111,2222,3333,4444,5555,6666,7777,8888,9999])
students_ids_number

array([1111, 2222, 3333, 4444, 5555, 6666, 7777, 8888, 9999])

In [20]:
students_ids_number_reg = students_ids_number #assignment operator generates another reference
print("id of student_ids_number",id(students_ids_number))
print("id of student_ids_number_reg",id(students_ids_number_reg))

id of student_ids_number 140354579850128
id of student_ids_number_reg 140354579850128


In [21]:
students_ids_number_reg[1] = 6969
print(students_ids_number_reg)
print(students_ids_number)

[1111 6969 3333 4444 5555 6666 7777 8888 9999]
[1111 6969 3333 4444 5555 6666 7777 8888 9999]


In [22]:
students_ids_number_cp = students_ids_number.copy() # array is copied to another array
print(students_ids_number_cp)


[1111 6969 3333 4444 5555 6666 7777 8888 9999]


In [23]:
print(students_ids_number_cp == students_ids_number)

[ True  True  True  True  True  True  True  True  True]


In [25]:
print("id of student_ids_number_cp",id(students_ids_number_cp)) # different id numbers 
print("id of student_ids_number",id(students_ids_number))

id of student_ids_number_cp 140354574228048
id of student_ids_number 140354579850128


In [26]:
students_ids_number[0] = 1000 # copy, copies the array into another
print('original: ', students_ids_number)
print('copy: ',students_ids_number_cp)

original:  [1000 6969 3333 4444 5555 6666 7777 8888 9999]
copy:  [1111 6969 3333 4444 5555 6666 7777 8888 9999]


In [27]:
students_ids_number_v = students_ids_number.view()

In [28]:
students_ids_number_v[0] = 2000 # view generates a reference
print('original: ', students_ids_number)
print('copy: ',students_ids_number_v)

original:  [2000 6969 3333 4444 5555 6666 7777 8888 9999]
copy:  [2000 6969 3333 4444 5555 6666 7777 8888 9999]


In [29]:
print(students_ids_number_cp.base) #None is generated if the data is copied

None


In [30]:
print(students_ids_number_v.base) # another array is generated since it is already a reference to another object or array.

[2000 6969 3333 4444 5555 6666 7777 8888 9999]


Reshaping arrays

In [31]:
first_arr = np.arange(1, 13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
second_arr = np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
 third_arr = np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [35]:
fourth_arr = np.reshape(first_arr,(4,4))
fourth_arr

ValueError: cannot reshape array of size 12 into shape (4,4)

In [36]:
fifth_arr = np.reshape(first_arr,(3,2,2)) #converted 1d array to 3d array
fifth_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [37]:
sixth_arr = np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
seventh_arr_flat = np.reshape(sixth_arr, -1) #flattened 2d array to 1d array
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [39]:
eighth_arr_flat = sixth_arr.flatten() #flatten, copies
print('eighth_arr_flat: ',eighth_arr_flat)
ninth_arr_rav = sixth_arr.ravel() #ravel, views
print('ninth_arr_rav: ', ninth_arr_rav)

eighth_arr_flat:  [1 2 3 4 5 6]
ninth_arr_rav:  [1 2 3 4 5 6]


In [40]:
eighth_arr_flat[0] = 100

In [41]:
ninth_arr_rav[0] = 200

In [42]:
print('eighth_arr_flat: ',eighth_arr_flat)
print('ninth_arr_rav: ', ninth_arr_rav)
print('sixth_arr: ', sixth_arr)

eighth_arr_flat:  [100   2   3   4   5   6]
ninth_arr_rav:  [200   2   3   4   5   6]
sixth_arr:  [[200   2]
 [  3   4]
 [  5   6]]


indexing and slicing arrays

In [43]:
twodim_arr = np.reshape(np.arange(12), (3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
twodim_arr[1,1]

5

In [45]:
twodim_arr[1]

array([4, 5, 6, 7])

In [46]:
threedim_arr = np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [47]:
threedim_arr[0,2,3]

13

In [48]:
threedim_arr[2,-1,-1]

59

In [49]:
onedim_arr = np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [51]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [52]:
onedim_arr[-3:]

array([7, 8, 9])

In [53]:
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [54]:
twodim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [55]:
twodim_arr[1,:]

array([4, 5, 6, 7])

In [56]:
twodim_arr[:,2]

array([ 2,  6, 10])

joining and splitting arrays

In [57]:
first_arr = np.arange(1,11)
second_arr = np.arange(11,21)
print('first_arr',first_arr)
print('second_arr',second_arr)

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


In [58]:
con_arr = np.concatenate((first_arr,second_arr)) # attaches arrays together
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
third_2darr = np.array([[1,2,3,4,5,],[6,7,8,9,10]])
third_2darr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
fourth_2darr = np.array([[11,12,13,14,15],[16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [63]:
con2d_arr = np.concatenate((third_2darr,fourth_2darr), axis = 1) #axis regulates the row and colums of the array
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [65]:
st_arr = np.stack((first_arr,second_arr)) # stacks vertically
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [66]:
hst_arr = np.hstack((first_arr,second_arr)) # stacks horizontally
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
vst_arr = np.vstack((first_arr,second_arr)) #stacks vertically
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [68]:
fifth_arr = np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
sp_arr = np.array_split(fifth_arr,4) #splits into 4 parts
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [70]:
print(sp_arr[1])

[4 5 6]


In [72]:
sp_arr = np.array_split(fifth_arr,8) #split into 8 parts
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [73]:
hs_arr = np.hsplit(third_2darr,5) #splits horizontally into 5 parts
hs_arr

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [74]:
vs_arr = np.vsplit(third_2darr,2) #splits vertically into 2 parts
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]