In [2]:
import numpy as np

adding, removing and sorting elements

In [4]:
first_arr = np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [5]:
new_frist_arr = np.insert(first_arr,3,4) # inserted 4 at index 3
new_frist_arr

array([1, 2, 3, 4, 5])

In [6]:
second_arr = np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [7]:
new_second_arr = np.append(second_arr, 5) # added 5 at the end
new_second_arr

array([1, 2, 3, 4, 5])

In [8]:
third_arr = np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [9]:
del_arr = np.delete(third_arr, 4) #deleted element at index 4
del_arr

array([1, 2, 3, 4])

In [10]:
integers_arr = np.random.randint(0,20,20)
integers_arr

array([18, 16,  7, 15,  0,  5,  7,  9, 14,  8,  9, 14, 15, 14,  0, 19,  2,
       15, 17,  7])

In [11]:
print(np.sort(integers_arr)) # sorted the array

[ 0  0  2  5  7  7  7  8  9  9 14 14 14 15 15 15 16 17 18 19]


In [13]:
integers_2dim_arr = np.array([[3,2,5,7,4],[5,0,8,3,1]]) #sorted the 2d array
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [14]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [15]:
colors = np.array(['violet', 'orange', 'yellow', 'white', 'black'])
colors

array(['violet', 'orange', 'yellow', 'white', 'black'], dtype='<U6')

In [16]:
print(np.sort(colors)) #sorted an array of strings

['black' 'orange' 'violet' 'white' 'yellow']


copies and views

In [18]:
students_ids_number = np.array([1111,2222,3333,4444,5555,6666,7777,8888,9999])
students_ids_number

array([1111, 2222, 3333, 4444, 5555, 6666, 7777, 8888, 9999])

In [20]:
students_ids_number_reg = students_ids_number #assignment operator generates another reference
print("id of student_ids_number",id(students_ids_number))
print("id of student_ids_number_reg",id(students_ids_number_reg))

id of student_ids_number 140354579850128
id of student_ids_number_reg 140354579850128


In [21]:
students_ids_number_reg[1] = 6969
print(students_ids_number_reg)
print(students_ids_number)

[1111 6969 3333 4444 5555 6666 7777 8888 9999]
[1111 6969 3333 4444 5555 6666 7777 8888 9999]


In [22]:
students_ids_number_cp = students_ids_number.copy() # array is copied to another array
print(students_ids_number_cp)


[1111 6969 3333 4444 5555 6666 7777 8888 9999]


In [23]:
print(students_ids_number_cp == students_ids_number)

[ True  True  True  True  True  True  True  True  True]


In [25]:
print("id of student_ids_number_cp",id(students_ids_number_cp)) # different id numbers 
print("id of student_ids_number",id(students_ids_number))

id of student_ids_number_cp 140354574228048
id of student_ids_number 140354579850128


In [26]:
students_ids_number[0] = 1000 # copy, copies the array into another
print('original: ', students_ids_number)
print('copy: ',students_ids_number_cp)

original:  [1000 6969 3333 4444 5555 6666 7777 8888 9999]
copy:  [1111 6969 3333 4444 5555 6666 7777 8888 9999]


In [27]:
students_ids_number_v = students_ids_number.view()

In [28]:
students_ids_number_v[0] = 2000 # view generates a reference
print('original: ', students_ids_number)
print('copy: ',students_ids_number_v)

original:  [2000 6969 3333 4444 5555 6666 7777 8888 9999]
copy:  [2000 6969 3333 4444 5555 6666 7777 8888 9999]


In [29]:
print(students_ids_number_cp.base) #None is ge

None


In [30]:
print(students_ids_number_v.base)

[2000 6969 3333 4444 5555 6666 7777 8888 9999]
