In [16]:
import numpy as np

array types and conversion btw types

In [2]:
integers = np.array([10,20,30,40,50]) #create a numpy array

In [3]:
print(integers)

[10 20 30 40 50]


In [4]:
integers[0]

10

In [5]:
integers[0] = 20
integers

array([20, 20, 30, 40, 50])

In [6]:
integers[0] = 21.5 #truncates the float value to a int64 value, because the dtype is int64
integers

array([21, 20, 30, 40, 50])

In [7]:
integers.dtype 

dtype('int64')

In [9]:
smaller_integers = np.array(integers, dtype=np.int8) #dtype can be changed while creating the array
smaller_integers

array([21, 20, 30, 40, 50], dtype=int8)

In [10]:
integers.nbytes #size in bytes of a int64 array

40

In [11]:
smaller_integers.nbytes #size in bytes of a int8 array

5

In [13]:
overflow = np.array([127, 128, 129], dtype = np.int8) #numpy arrays can fix the overflow
overflow

array([ 127, -128, -127], dtype=int8)

In [14]:
floats = np.array([1.2,2.3,3.4,5.1,8.3]) 
print(floats)

[1.2 2.3 3.4 5.1 8.3]


In [15]:
floats.dtype

dtype('float64')

multidimensional arrays

In [19]:
nums = np.array([[1,2,3,4,5], [6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
nums[0][0] #[row,column], [0,0] is the first elememt in the matrix 

1

In [21]:
nums[1][4] #the last element in the matrix

10

In [22]:
nums.ndim #checks the dimension of the array

2

In [25]:
multi_arr = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]]) #a 3D matrix
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
multi_arr[1][0][2] # 2nd row in the 3d matrix, 1st row in the 2D matrix, last element in the 1d matrix

9

creating arrays from lists and other python structures

In [27]:
first_list = [1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [29]:
first_array= np.array(first_list) #converted python list to numpy array
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
second_list = [1,2,3,-1.23,50,128000.56,4.56]

In [31]:
second_array = np.array(second_list)

In [32]:
second_array #numpy changes the type of each element to float64

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [33]:
second_array.dtype

dtype('float64')

In [34]:
third_list = ["ann", 11111,"peter", 22222,"susan", 33333, "john"]

In [35]:
third_array = np.array(third_list)

In [36]:
third_array #it represents a combination of numbers and letters as <U21

array(['ann', '11111', 'peter', '22222', 'susan', '33333', 'john'],
      dtype='<U21')

In [38]:
first_tuple = (1,2,3,4,5)

In [39]:
array_from_tuple = np.array(first_tuple)

In [40]:
array_from_tuple #a python tuple is converted to a regular numpy array

array([1, 2, 3, 4, 5])

In [42]:
array_from_tuple.dtype

dtype('int64')

In [43]:
multi_dim_list = [[[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]]]

In [44]:
array_from_multi_dim_list = np.array(multi_dim_list)

In [45]:
array_from_multi_dim_list # a 2D matrix can be converted into a NumPy array, wihtout any changes.

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Intrinsic NumPy array creation

In [47]:
integers_array = np.arange(10) #creates an array from 1 to 9
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
integers_second_array = np.arange(100, 130) #creates an array from 100 to 129
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [49]:
integers_third_array = np.arange(100, 151,2) # from 100 to 150 with an interval of 2
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [50]:
first_floats_arr = np.linspace(10,20) #array of float values from 10.0 to 20.0(included)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [51]:
second_floats_arr = np.linspace(10, 20, 5) #array of float values from 10.0 to 20.0(included) with 5 elements equally spaced
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [52]:
first_rand_arr = np.random.rand(10) #an array of 10 random elements btw 0 and 1
first_rand_arr

array([0.87094308, 0.5447745 , 0.85708372, 0.00312175, 0.50023042,
       0.76326606, 0.91891815, 0.13843596, 0.10711673, 0.84333568])

In [53]:
second_rand_arr = np.random.rand(1,3) # an array of random elements of 1 row and 3 columns
second_rand_arr

array([[0.82638329, 0.22096623, 0.61739552]])

In [55]:
third_rand_arr = np.random.randint(0, 100, 20) # a random array from 0 to 100 containing 20 elemnents.
third_rand_arr

array([26, 90, 43, 96, 39, 55,  0, 56, 34, 77,  4, 83, 51, 37, 28, 94, 69,
       10, 24, 98])

Creating arrays filled with constant values

In [58]:
first_z_array = np.zeros(5) #creates an array of 0's with 5 elements
first_z_array

array([0., 0., 0., 0., 0.])

In [59]:
second_z_array = np.zeros((4,5)) # creates a 2d array of 0's with 4 row, 5 column
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
first_ones_array = np.ones(6)
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [61]:
second_ones_array = np.ones((7,8))
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
third_ones_array = np.ones((4,5), dtype=int) #type changed to int
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
first_fill_array = np.empty(10, dtype=int) # creates an empty array with 10 elements and type int
first_fill_array.fill(12) # fills all the elements with 12
first_fill_array # fill is used to create a 1d array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [65]:
first_full_array = np.full(5,10) #1d array with 5 elements all filled with 10
first_full_array # full can be used to create 1d and 2d arrays

array([10, 10, 10, 10, 10])

In [67]:
second_full_array = np.full((4,5), 8) #creates a 2d array 4 row, 5 columns, all filled with 8
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

Finding the shape and size of the array

In [68]:
first_arr = np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
second_arr = np.linspace((0,0), (10, 10), 5) #creates a 2d array that starts from (0,0) to (10, 10) with a step of 5
second_arr

array([[ 0. ,  0. ],
       [ 2.5,  2.5],
       [ 5. ,  5. ],
       [ 7.5,  7.5],
       [10. , 10. ]])

In [71]:
third_arr = np.full((2,2,2), 10) # a 3d array wiith 10 for all elements
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [72]:
np.shape(first_arr) # calculates the number of rows and columns

(20,)

In [73]:
np.shape(second_arr)

(5, 2)

In [74]:
np.shape(third_arr)

(2, 2, 2)

In [75]:
np.size(first_arr) # calculates the number of elements present

20

In [76]:
np.size(second_arr)

10

In [77]:
np.size(third_arr)

8